Tests
IdeaSeeker/TheGreatCombinator pull request #13
Opened 2020-05-21 08:33 UTC by IdeaSeeker

2020-05-21 22:43 UTC, devcrocod requested changes

2020-05-21 22:43 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +            val count = Array(length + 1) { IntArray(length + 1) }
Здесь можно взять `Map<Pair<Int, Int>, Int>`. Тогда вычисление average будет выглядеть примерно так: `count.values.sumBy { it * it } / possibleAnswers.size`

2020-05-21 22:43 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        magicSpeedUp.forEach {
здесь не подойдет `maxBy`?

2020-05-21 22:43 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        val magicSpeedUp = possibleAnswers.toList().shuffled()
Зачем преобразовывать в List?

2020-05-21 22:43 UTC, devcrocod commented on app/src/test/java/com/mkn/thegreatcombinator/AlgorithmTest.kt
> +    fun restart_testValidation() {
Зачем нужен этот тест?

2020-05-21 22:43 UTC, devcrocod commented on app/src/test/java/com/mkn/thegreatcombinator/UtilityTest.kt
> +            OneTest("1546", "4535", 1, 1),
такое количество проверок особо ни к чему. Потестировать обычные и крайние случаи.

2020-05-22 08:40 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +            in 1..99 -> optimalChoice() // Медленный алгоритм
Вынес в константу.
Проверка такая, потому что `optimalChoice` работает за квадрат от размера `possibleAnswers`, тогда на вызов тратится порядка 10^4 операций, и всё летает :)

2020-05-22 08:41 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
>      private fun generatePossible(prefix: String = "") {
Какой рандом? Где? Не понял

2020-05-22 08:44 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +            val count = Array(length + 1) { IntArray(length + 1) }
Ага, только `Map` либо за _log_, либо с большой константой работает. Эта функция итак очень тяжелая в плане времени работы

2020-05-22 08:44 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        magicSpeedUp.forEach {
Да, исправлю

2020-05-22 08:45 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        val magicSpeedUp = possibleAnswers.toList().shuffled()
Тут всё хорошо. Не зря же названо именно `magicSpeedUp` :)

2020-05-22 08:50 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +            val count = Array(length + 1) { IntArray(length + 1) }
В каком месте map будет работать за log?

2020-05-22 08:50 UTC, IdeaSeeker commented on app/src/test/java/com/mkn/thegreatcombinator/AlgorithmTest.kt
> +    fun restart_testValidation() {
Как понять зачем?
В какой-то старой версии вообще не было метода `restart`, отчего всё работало не так как надо, поэтому я решил добавить тест на это

2020-05-22 08:50 UTC, IdeaSeeker commented on app/src/test/java/com/mkn/thegreatcombinator/UtilityTest.kt
> +            OneTest("1546", "4535", 1, 1),
Да, наверное

2020-05-22 08:50 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/Utility.kt
> +    val length = answer.length
Убрал

2020-05-22 08:51 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        val magicSpeedUp = possibleAnswers.toList().shuffled()
Посмотри на [shuffled](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/shuffled.html)

2020-05-22 08:54 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +            val count = Array(length + 1) { IntArray(length + 1) }
Ну если деревом, то за log. Если HashMap, то всё равно долго

2020-05-22 08:55 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        val magicSpeedUp = possibleAnswers.toList().shuffled()
Посмотрел. Написано, он работает с `List`

2020-05-22 08:57 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        val magicSpeedUp = possibleAnswers.toList().shuffled()
А, понял, да))

2020-05-22 09:01 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
>      private fun generatePossible(prefix: String = "") {
Происходит очень много лишних вызовов. Пока префикс не станет нужной длины, пока не переберет все префиксы уже добавленные в `possibleAnswers`.
Рандом здесь не очень, но `possibleAnswers` это на самом деле `LinkedHashSet`, почему бы этим не воспользоваться? Брать последний элемент и увеличивать его на единицу

2020-05-22 09:07 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
>      private fun generatePossible(prefix: String = "") {
Что такое увеличить на 1 число 2366, если максимальная цифра 6? Это же надо пройти по строке, чему-то присвоить 1, что-то увеличить, чтобы получить в конце 2411.
Тем более такой перебор позволяет отсекать варианты на раннем этапе, что я и хочу сейчас сделать. 
Или я неправильно понял, что ты имеешь ввиду?

2020-05-22 09:14 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +            val count = Array(length + 1) { IntArray(length + 1) }
Почему? Сразу задать размер HashMap, чтобы не было копирования. А доступ по ключам за O(1), зато потом проще по значениям пробегать.

2020-05-22 09:24 UTC, IdeaSeeker commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +            val count = Array(length + 1) { IntArray(length + 1) }
Да, убедили

2020-05-22 09:34 UTC, devcrocod commented on app/src/test/java/com/mkn/thegreatcombinator/AlgorithmTest.kt
> +    fun restart_testValidation() {
А, хорошо. Неправильно понял

2020-05-22 12:24 UTC, devcrocod requested changes

2020-05-22 12:24 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
>      private fun generatePossible(prefix: String = "") {
Тут проблема что нулей нет, а так BigInteger есть:
`(BigInteger(possibleAnswers.last(), maxDigit) + BigInteger.ONE).toString(maxDigit)`
Правда он в случае 2366 + 1 даст 2400

2020-05-22 21:40 UTC, IdeaSeeker commented
Теперь должно летать, тесты говорят, что функция, которая раньше работала > 12 секунд, теперь выполняется за 130 мс в среднем.
Правда, код увеличился раза в 2 и стал менее прозрачным.

2020-05-23 17:25 UTC, devcrocod requested changes

2020-05-23 17:25 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        val aRequired = aBound - aCount
Добавить оператор minus для Pair<Int, Int>

2020-05-23 17:25 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +    private fun checkAllConditions(attempt: String,
если заменить изначальные списки на одну мапу, этот метод будет не нужен
также как и все связанные с ним

2020-05-23 17:25 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/logic/SolverAI.kt
> +        return aCount <= aBound && bCount <= bBound
Переопределить compareTo для Pair<Int, Int>

2020-05-24 08:44 UTC, devcrocod approved these changes
approve

2020-05-24 10:53 UTC, merged