Settings activity
IdeaSeeker/TheGreatCombinator pull request #14
Opened 2020-05-21 18:47 UTC by bagrorg

2020-05-21 18:56 UTC, IdeaSeeker commented
_Сыныптық_

2020-05-24 09:00 UTC, devcrocod requested changes

2020-05-24 10:56 UTC, bagrorg commented on app/src/main/java/com/mkn/thegreatcombinator/SettingsActivity.kt
> +    val APP_PREFERENCES_NAME = "Settings"
val разве не подразумевает read-only?

2020-05-24 11:05 UTC, bagrorg commented on app/src/main/java/com/mkn/thegreatcombinator/SettingsActivity.kt
> +            if (button.text.toString().toInt() == pref.getInt(APP_PREFERENCES_LENGTH, 4)) {
button.text все равно будет возвращать 'CharSequence!'

2020-05-24 11:32 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/SettingsActivity.kt
> +            if (button.text.toString().toInt() == pref.getInt(APP_PREFERENCES_LENGTH, 4)) {
Хорошо

2020-05-24 11:35 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/SettingsActivity.kt
> +    val APP_PREFERENCES_NAME = "Settings"
Подразумевает, это на усмотрение. const - говорит только о том что проперти будут доступны во время компиляции, здесь это не так важно.

2020-05-24 11:36 UTC, bagrorg commented on app/src/main/java/com/mkn/thegreatcombinator/SettingsActivity.kt
> +    val APP_PREFERENCES_NAME = "Settings"
Просто как я понял const невозможен на полях класса (либо я что-то перепутал)

2020-05-24 11:39 UTC, devcrocod commented on app/src/main/java/com/mkn/thegreatcombinator/SettingsActivity.kt
> +                    .putInt(APP_PREFERENCES_LENGTH, button.text.toString().toInt()).apply()
принято писать с новой строчки, примерно так:
```
pref.edit()
       .remove(APP_PREFERENCES_LENGTH)
       .putInt(APP_PREFERENCES_LENGTH, button.text.toString().toInt())
       .apply()
```

2020-05-24 11:40 UTC, devcrocod approved these changes
👍

2020-05-24 11:47 UTC, merged